version: '3'

services:
  app:
    build: .
    image: naoki0513/nuxt-sample
    container_name: nuxt-sample
    ports:
      - '49160:8000'
    restart: always
    volumes:
      - '.:/user/src/app'
